spring:
  datasource:
    url: jdbc:h2:file:/Users/jamiecoller/Desktop/Projects/databases
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true